/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	debugerv1 "github.com/zhfg/k8s-crd-debug/pkg/apis/debuger/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDebugerTypes implements DebugerTypeInterface
type FakeDebugerTypes struct {
	Fake *FakeK8sV1
	ns   string
}

var debugertypesResource = schema.GroupVersionResource{Group: "k8s.family-zhang.com", Version: "v1", Resource: "debugertypes"}

var debugertypesKind = schema.GroupVersionKind{Group: "k8s.family-zhang.com", Version: "v1", Kind: "DebugerType"}

// Get takes name of the debugerType, and returns the corresponding debugerType object, and an error if there is any.
func (c *FakeDebugerTypes) Get(ctx context.Context, name string, options v1.GetOptions) (result *debugerv1.DebugerType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(debugertypesResource, c.ns, name), &debugerv1.DebugerType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*debugerv1.DebugerType), err
}

// List takes label and field selectors, and returns the list of DebugerTypes that match those selectors.
func (c *FakeDebugerTypes) List(ctx context.Context, opts v1.ListOptions) (result *debugerv1.DebugerTypeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(debugertypesResource, debugertypesKind, c.ns, opts), &debugerv1.DebugerTypeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &debugerv1.DebugerTypeList{ListMeta: obj.(*debugerv1.DebugerTypeList).ListMeta}
	for _, item := range obj.(*debugerv1.DebugerTypeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested debugerTypes.
func (c *FakeDebugerTypes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(debugertypesResource, c.ns, opts))

}

// Create takes the representation of a debugerType and creates it.  Returns the server's representation of the debugerType, and an error, if there is any.
func (c *FakeDebugerTypes) Create(ctx context.Context, debugerType *debugerv1.DebugerType, opts v1.CreateOptions) (result *debugerv1.DebugerType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(debugertypesResource, c.ns, debugerType), &debugerv1.DebugerType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*debugerv1.DebugerType), err
}

// Update takes the representation of a debugerType and updates it. Returns the server's representation of the debugerType, and an error, if there is any.
func (c *FakeDebugerTypes) Update(ctx context.Context, debugerType *debugerv1.DebugerType, opts v1.UpdateOptions) (result *debugerv1.DebugerType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(debugertypesResource, c.ns, debugerType), &debugerv1.DebugerType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*debugerv1.DebugerType), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDebugerTypes) UpdateStatus(ctx context.Context, debugerType *debugerv1.DebugerType, opts v1.UpdateOptions) (*debugerv1.DebugerType, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(debugertypesResource, "status", c.ns, debugerType), &debugerv1.DebugerType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*debugerv1.DebugerType), err
}

// Delete takes name of the debugerType and deletes it. Returns an error if one occurs.
func (c *FakeDebugerTypes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(debugertypesResource, c.ns, name), &debugerv1.DebugerType{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDebugerTypes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(debugertypesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &debugerv1.DebugerTypeList{})
	return err
}

// Patch applies the patch and returns the patched debugerType.
func (c *FakeDebugerTypes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *debugerv1.DebugerType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(debugertypesResource, c.ns, name, pt, data, subresources...), &debugerv1.DebugerType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*debugerv1.DebugerType), err
}
