apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
      - image: theiaide/theia:0.16.1
        imagePullPolicy: IfNotPresent
        name: sidecar-theia
        volumeMounts:
        - mountPath: /data/
          name: share-data
      volumes:
      - emptyDir: {}
        name: data
      - emptyDir: {}
        name: share-data
