/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/zhfg/k8s-crd-debug/pkg/apis/debuger/v1"
	scheme "github.com/zhfg/k8s-crd-debug/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DebugerTypesGetter has a method to return a DebugerTypeInterface.
// A group's client should implement this interface.
type DebugerTypesGetter interface {
	DebugerTypes(namespace string) DebugerTypeInterface
}

// DebugerTypeInterface has methods to work with DebugerType resources.
type DebugerTypeInterface interface {
	Create(ctx context.Context, debugerType *v1.DebugerType, opts metav1.CreateOptions) (*v1.DebugerType, error)
	Update(ctx context.Context, debugerType *v1.DebugerType, opts metav1.UpdateOptions) (*v1.DebugerType, error)
	UpdateStatus(ctx context.Context, debugerType *v1.DebugerType, opts metav1.UpdateOptions) (*v1.DebugerType, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.DebugerType, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.DebugerTypeList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DebugerType, err error)
	DebugerTypeExpansion
}

// debugerTypes implements DebugerTypeInterface
type debugerTypes struct {
	client rest.Interface
	ns     string
}

// newDebugerTypes returns a DebugerTypes
func newDebugerTypes(c *DebugerV1Client, namespace string) *debugerTypes {
	return &debugerTypes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the debugerType, and returns the corresponding debugerType object, and an error if there is any.
func (c *debugerTypes) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.DebugerType, err error) {
	result = &v1.DebugerType{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("debugertypes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DebugerTypes that match those selectors.
func (c *debugerTypes) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DebugerTypeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.DebugerTypeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("debugertypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested debugerTypes.
func (c *debugerTypes) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("debugertypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a debugerType and creates it.  Returns the server's representation of the debugerType, and an error, if there is any.
func (c *debugerTypes) Create(ctx context.Context, debugerType *v1.DebugerType, opts metav1.CreateOptions) (result *v1.DebugerType, err error) {
	result = &v1.DebugerType{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("debugertypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(debugerType).
		Do().
		Into(result)
	return
}

// Update takes the representation of a debugerType and updates it. Returns the server's representation of the debugerType, and an error, if there is any.
func (c *debugerTypes) Update(ctx context.Context, debugerType *v1.DebugerType, opts metav1.UpdateOptions) (result *v1.DebugerType, err error) {
	result = &v1.DebugerType{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("debugertypes").
		Name(debugerType.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(debugerType).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *debugerTypes) UpdateStatus(ctx context.Context, debugerType *v1.DebugerType, opts metav1.UpdateOptions) (result *v1.DebugerType, err error) {
	result = &v1.DebugerType{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("debugertypes").
		Name(debugerType.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(debugerType).
		Do().
		Into(result)
	return
}

// Delete takes name of the debugerType and deletes it. Returns an error if one occurs.
func (c *debugerTypes) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("debugertypes").
		Name(name).
		Body(&opts).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *debugerTypes) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("debugertypes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do().
		Error()
}

// Patch applies the patch and returns the patched debugerType.
func (c *debugerTypes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DebugerType, err error) {
	result = &v1.DebugerType{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("debugertypes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do().
		Into(result)
	return
}
